### PR TITLE
Add py.typed file

### LINKED ISSUE #77: Adding py.typed file
Hi,

it would be great if you could expose your typing hints by adding a `py.typed` file. Can you please consider this?

Thanks!

### PR DESCRIPTION
**Pull request by Akuli**
Fixes #77 

This commit does the same exact thing, in a different project, that also uses poetry: https://github.com/br3ndonland/inboard/commit/2af1ffa3978b0efe9c68c46694fd3b61d2b8924c

### CODE REVIEW

**Comment by afonasev** [comment]
Ok. Thank you for contribution!

**Comment by kkirsche** [comment]
Are there plans to deploy an updated version of the plugin with this marker?

**Comment by sobolevn** [comment]
@afonasev can you please release the version with `py.typed` included? This will allow us to drop this project from `typeshed`: https://github.com/python/typeshed/tree/main/stubs/flake8-plugin-utils

It would be very helpful! 👍

**Comment by afonasev** [comment]
@sobolevn done! version 1.3.3 released

**Pull request merged**
